In [1]:
import numpy as np
np.array([2,4,56,422,32,1]) 
a = np.array([2,4,56,422,32,1]) 

In [2]:
print(a)

[  2   4  56 422  32   1]


In [3]:
type(a)

numpy.ndarray

In [4]:
new = np.array([[45,34,22,2],[24,55,3,22]])

In [5]:
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [7]:
np.array ( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [10]:
np.array([11,23,44] , dtype =float)

array([11., 23., 44.])

In [9]:
np.array([11,23,44] , dtype =bool) 

array([ True,  True,  True])

In [ ]:
np.array([11,23,44] , dtype =complex)

In [11]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.random.random((4,3))

array([[0.5345221 , 0.86686871, 0.49170863],
       [0.04999541, 0.55457476, 0.15564424],
       [0.87067799, 0.93443997, 0.38020108],
       [0.3391457 , 0.52541323, 0.93282146]])

In [16]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])